import {FlyGPU} from '../gpu-model.mjs';
import {Engine,twistToWrench,clearance} from '../engine.mjs';
const $=id=>document.getElementById(id),meta=await(await fetch('../model/model.json')).json();let gpu,stop=false;const reports=[];
const maxdiff=(a,b)=>{const other=b.flat(Infinity);return Math.max(...a.flat(Infinity).map((v,i)=>Math.abs(v-other[i])));};
async function save(report){report.timing=gpu?.timing;reports.push(report);$('results').textContent=JSON.stringify(reports,null,2);try{await fetch('/test-report',{method:'POST',body:JSON.stringify(report)});}catch{}}
async function task(fn){try{stop=false;for(const id of ['init','parity','run'])$(id).disabled=true;await fn();}catch(e){$('status').textContent='ERROR: '+e.stack;await save({error:e.stack});}finally{if(gpu){$('parity').disabled=$('run').disabled=false;}else $('init').disabled=false;}}
$('stop').onclick=()=>{stop=true;};
$('bench').onclick=()=>task(async()=>{if(!gpu)throw Error('Initialize first');gpu.reset();const rows=(await(await fetch('../model/parity.json')).json()).rows;const timings=[];for(const row of rows.slice(0,5)){await gpu.step(row.obs);timings.push(gpu.timing);}await save({type:'benchmark',timings});});
$('init').onclick=()=>task(async()=>{const t=performance.now();gpu=await FlyGPU.create(meta,p=>$('status').textContent=`Loading ${Math.round(100*p.received/p.total)}%`);$('status').textContent='Full model ready';await save({type:'init',seconds:(performance.now()-t)/1000,adapter:gpu.adapterInfo});});
$('parity').onclick=()=>task(async()=>{gpu.reset();const rows=(await(await fetch('../model/parity.json')).json()).rows;let features=0,means=0,precisions=0;const t=performance.now();for(let i=0;i<rows.length&&!stop;i++){const r=rows[i],out=await gpu.step(r.obs),mean=twistToWrench(out.twist,r.obs,meta);features=Math.max(features,maxdiff(out.features,r.feature));means=Math.max(means,maxdiff(mean,r.mean));precisions=Math.max(precisions,maxdiff(out.precision,r.precision));$('status').textContent=`Parity ${i+1}/${rows.length}`;}await save({type:'parity',ticks:rows.length,seconds:(performance.now()-t)/1000,features,means,precisions});$('status').textContent='Parity complete';});
$('run').onclick=()=>task(async()=>{const engine=new Engine(meta,gpu);for(const seed of $('seeds').value.split(',').map(Number)){if(stop)break;engine.reset(seed);const t=performance.now();let minClearance=Infinity,maxAngle=0;while(!engine.done&&!stop){await engine.step();minClearance=Math.min(minClearance,clearance(engine.state,engine.walls,meta));maxAngle=Math.max(maxAngle,Math.abs(engine.state[2]));if(engine.tick%10===0)$('status').textContent=`Seed ${seed}: gate ${engine.stage}/4, tick ${engine.tick}`;}await save({type:'rollout',seed,ticks:engine.tick,success:engine.success,stage:engine.stage,contacts:engine.contacts,minClearance,maxAngle,seconds:(performance.now()-t)/1000,state:engine.state});}$('status').textContent=stop?'Stopped':'Rollouts complete';});
